package metadataapis;

public enum EntityNames {

    ADDRESS,
    DOCUMENTATION,
    ELEMENT,
    IDENTIFIER,
    LEGALNAME,
    PARAMETER,
    QUANTITATIVEVALUE,
    LOCATION,
    PERIODOFTIME,
    CATEGORY,
    CATEGORYSCHEME,
    CONTACTPOINT,
    DATAPRODUCT,
    DISTRIBUTION,
    EQUIPMENT,
    FACILITY,
    MAPPING,
    OPERATION,
    ORGANIZATION,
    PERSON,
    SOFTWAREAPPLICATION,
    SOFTWARESOURCECODE,
    WEBSERVICE,
    RELATION
}
